#!/bin/bash
# Build a lightweight, double-clickable "Soundboard Snag.app" for macOS.
#
# The app wraps the Python already on this machine (no PyInstaller, no bundled
# runtime). It embeds the ABSOLUTE python3 path and repo path at build time,
# because apps launched from Finder get a stripped PATH that usually omits
# /Library/Frameworks/.../bin and /usr/local/bin. On launch it applies the
# CA-cert fix (python.org Python ships without a system trust store), starts the
# --serve web server, opens the browser, and stops the server when you quit the
# app from the Dock.
#
# Re-run this script after moving the repo or upgrading Python.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PY="$(command -v python3 || true)"
[ -n "$PY" ] || { echo "error: python3 not found on PATH" >&2; exit 1; }
[ -f "$REPO/soundboard-snag.py" ] || { echo "error: soundboard-snag.py not next to repo root ($REPO)" >&2; exit 1; }

APP="$REPO/Soundboard Snag.app"
MACOS="$APP/Contents/MacOS"
RES="$APP/Contents/Resources"

rm -rf "$APP"
mkdir -p "$MACOS" "$RES"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Soundboard Snag</string>
  <key>CFBundleDisplayName</key><string>Soundboard Snag</string>
  <key>CFBundleIdentifier</key><string>com.soundboardsnag.app</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
  <key>NSHighResolutionCapable</key><true/>
  <!-- Agent app: no Dock icon, no menu bar, and crucially no perpetual Dock
       bounce for a windowless background process. Quit via the web UI's Stop
       button (POST /api/shutdown). -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST

# Write the launcher with the resolved REPO/PY baked in.
launcher="$MACOS/launcher"
cat > "$launcher" <<LAUNCHER
#!/bin/bash
# Generated by scripts/build-macos-app.sh — do not edit by hand; re-run the build.
REPO="$REPO"
PY="$PY"
PORT=8765
LAUNCHER

cat >> "$launcher" <<'LAUNCHER'
URL="http://127.0.0.1:$PORT"

# If the repo moved, fall back to resolving it relative to this .app, then to PATH.
if [ ! -f "$REPO/soundboard-snag.py" ]; then
  rel="$(cd "$(dirname "$0")/../../.." && pwd)"
  [ -f "$rel/soundboard-snag.py" ] && REPO="$rel"
fi
[ -x "$PY" ] || PY="$(command -v python3 || true)"
if [ -z "$PY" ]; then
  /usr/bin/osascript -e 'display alert "Soundboard Snag" message "Python 3 was not found. Install it from python.org, then re-run scripts/build-macos-app.sh."'
  exit 1
fi
cd "$REPO" || { /usr/bin/osascript -e 'display alert "Soundboard Snag" message "Could not find the app files. Re-run scripts/build-macos-app.sh."'; exit 1; }

# Save grabbed sounds somewhere sensible (not inside the repo this app launches from).
DEST="$HOME/Downloads/Soundboard Snag"

port_up() { "$PY" -c "import socket; socket.create_connection(('127.0.0.1',$PORT),0.3).close()" 2>/dev/null; }

# Already running? Just focus the browser and quit this instance (the running
# one keeps serving) — avoids a second server on the same port.
if port_up; then open "$URL"; exit 0; fi

# CA-cert bundle fix (python.org Python lacks a system trust store).
CERT="$("$PY" -m certifi 2>/dev/null || true)"
[ -n "$CERT" ] && export SSL_CERT_FILE="$CERT"

# Run the server as this app's FOREGROUND child and block on it. The app is an
# LSUIElement agent (Info.plist), so a windowless blocking process does NOT
# bounce the Dock. Keeping the server in-process (no nohup/detach) avoids it
# being reaped when a Finder-launched app's process group is torn down. It stays
# up until you click "Stop" in the web UI (POST /api/shutdown → server exits →
# wait returns → app quits) or the app is force-quit.
LOG="${TMPDIR:-/tmp}/soundboard-snag-serve.log"
"$PY" soundboard-snag.py --serve --host 127.0.0.1 --port "$PORT" -d "$DEST" >"$LOG" 2>&1 &
SERVER_PID=$!
trap 'kill "$SERVER_PID" 2>/dev/null' TERM INT EXIT

for _ in $(seq 1 60); do port_up && break; sleep 0.2; done
open "$URL"
wait "$SERVER_PID"
LAUNCHER

chmod +x "$launcher"

echo "Built: $APP"
echo "  python: $PY"
echo "  repo:   $REPO"
echo "Double-click it in Finder, or run: open \"$APP\""
